 platform :ios, '9.0'

target 'Swift_Sudoku_Solver' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Swift_Sudoku_Solver

  pod 'SnapKit'

end
